
spring:
  profiles:
    include: >
      actuator,
      chaos-engineering,
      data-source,
      dslogging,
      feign,
      jpa,
      kafka,
      license,
      logging,
      messages,
      rest-template,
      security,
      swagger
