server:
  port: 8080
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
spring:
  application:
    name: gateway
  cloud:
    gateway:
      routes:
      - id: eureka-gui
        uri: lb://servicediscovery
        predicates:
        - Path=/discovery/**
        filters:
        - StripPrefix=1
      - id: eureka-static
        uri: lb://servicediscovery
        predicates:
        - Path=/eureka/**
      - id: demo
        uri: lb://demo
        predicates:
        - Path=/demo/**
