
spring:
  kafka:
    bootstrap-servers: ${KAFKA_URL}
  cloud:
    stream:
      binders:
        binderName:
          type: kafka
#      bindings:
#        dq-mdp-versions-object-versions-in:
#          destination: dq-mdp-versions-object-versions-in
#        auditEventChannal:
#          destination: mdpAuditEvent
    
logging:
  level:
    kafka: ${LOGGING_KAFKA_LEVEL:INFO}
    org.apache.kafka.clients: ${LOGGING_KAFKA_LEVEL:INFO}
    org.springframework.kafka.listener: ${LOGGING_KAFKA_LEVEL:INFO}
